local hasResetAllBeenCalled = true

function onClick()
    noctalia.togglePanel("mel/pomodoro:panel")
end

local function render(state)
    if not state or not state.sessionPtr then
        barWidget.render(ui.glyph({
            color = "on_surface",
            name = noctalia.getConfig("widget-glyph-main"),
        }))
        return
    end

    local color = if state.isRunning then "primary" else "on_surface_variant"
    local name =
        if hasResetAllBeenCalled then 
            noctalia.getConfig("widget-glyph-main")
        else
            if state.sessionPtr.stage == 1 then
                noctalia.getConfig("widget-glyph-work")
            else noctalia.getConfig("widget-glyph-break")

    local content = { ui.glyph ({ color = color, name = name }) }

    local hours = math.floor(state.secondsLeft / 3600)
    local mins = math.floor((state.secondsLeft % 3600) / 60)
    local secs = state.secondsLeft % 60

    local labelTime =
      if hours == 0 then
          string.format("%02d\n%02d", mins, secs)
      else
          string.format("%02d\n%02d\n%02d", hours, mins, secs)

    if not hasResetAllBeenCalled then
        table.insert(content, ui.label({
            text = labelTime,
            textAlign = "center",
            color = color
        }))
    end

    local container = ui.column
    barWidget.render(container({ gap = 4, align = "center", justify = "center" }, content))
end

--- main
local function refresh()
    render(noctalia.state.get("mel-pomodoro.state"))
end

render(noctalia.state.get("mel-pomodoro.state"))

noctalia.state.watch("mel-pomodoro.nextCommand", function(command)
    if command == "toggle" then
        hasResetAllBeenCalled = false
    elseif command == "resetAll" then
        hasResetAllBeenCalled = true
        refresh()
    end
end)

noctalia.state.watch("mel-pomodoro.state", function(state)
    refresh()
end)

noctalia.state.watch("mel-pomodoro.sessionData", function(_sessionData)
    refresh()
end)
